#include "swca.h"

TASKBAR_APPEARANCE REGULAR_APPEARANCE = { swca::ACCENT::ACCENT_ENABLE_TRANSPARENTGRADIENT, 0x0 };
TASKBAR_APPEARANCE MAXIMISED_APPEARANCE = { swca::ACCENT::ACCENT_ENABLE_BLURBEHIND, 0xaa000000 };
TASKBAR_APPEARANCE START_APPEARANCE = { swca::ACCENT::ACCENT_NORMAL, 0x0 };
TASKBAR_APPEARANCE CORTANA_APPEARANCE = { swca::ACCENT::ACCENT_NORMAL, 0x0 };
TASKBAR_APPEARANCE TIMELINE_APPEARANCE = { swca::ACCENT::ACCENT_NORMAL, 0x0 };